# Generated by Django 4.2 on 2023-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='developmentprogram_1week',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='developmentprogram_2week',
        ),
        migrations.AddField(
            model_name='extra',
            name='developmentprogram',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '1 WEEK'), (5, '2 WEEK')], null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
