# Generated by Django 4.2 on 2023-04-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_extra_developmentprogram_1week_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
