# Generated by Django 4.2 on 2023-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_delete_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_date01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='iidate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='iiname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interaction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Reputed Institution Abroad Or Institution Of Eminence in India Or National Research Laboratories'), (3, 'Institution/Industry')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='oneweek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='program_name01',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='program_name02',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twoweek',
            field=models.BooleanField(default=False),
        ),
    ]
