# Generated by Django 4.2 on 2023-04-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_student_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='y2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='y3',
            field=models.IntegerField(default=0),
        ),
    ]
