# Generated by Django 4.2 on 2023-04-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_student_y1_alter_student_y2_alter_student_y3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
